name: 'closed door | Open Window'
favicon: null
layout_spectrum: 0.41827
typography_spectrum: 0.35191
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040308'
    - '#eeeeee'
    - '#b55000'
    - '#ff7000'
    - '#fdc624'
  brandStrength: 0.6875
  lightness: 0.8411986967548728
  saturation: 0.06056224484927952
  rhythmicContrast: 0.8864216122310609
purpose: []
